function createfigure(X1, YMatrix1)
%CREATEFIGURE(X1,YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 20-Mar-2012 14:45:41

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'YScale','log','YMinorTick','on',...
    'XScale','log',...
    'XMinorTick','on',...
    'FontSize',16,...
    'FontName','Times');
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[6 20]);
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to loglog
loglog1 = loglog(X1,YMatrix1,'Parent',axes1,'MarkerSize',2,'LineWidth',4);
set(loglog1(1),'LineStyle','--','Color',[0 0 1],'DisplayName','FIFO+FIFO');
set(loglog1(2),'LineStyle',':','DisplayName','FIFO+LAS','Color',[0 0 0]);
set(loglog1(3),'Marker','.','Color',[0 0.5 0],'DisplayName','LAS+FIFO');
set(loglog1(4),'LineStyle','-.','Color',[1 0 0],'DisplayName','LAS+LAS');

% Create xlabel
xlabel('File size in MSS','FontSize',16,'FontName','Times');

% Create ylabel
ylabel('Mean Response time (s)','FontSize',16,'FontName','Times');

% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Location','SouthEast');
                namefile=sprintf('./EPS/issue2/mg1_variant_fs_exp_%d_%d_th.eps', index_load,index_up);
                print('-depsc',namefile);
                saveas(gcf,sprintf('./EPS/issue2/mg1_variant_fs_exp_%d_%d_th.fig', index_load,index_up));      

